# Array creation

Create a 1-dimensional array of integers from 1 to 10.

In [1]:
import numpy as np

In [8]:
my_array = np.array(range(1,11))
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(my_array)

numpy.ndarray

Create a 2-dimensional array with random float values of shape (3, 4).

In [10]:
np.random.rand(3,4)

array([[0.81888235, 0.32730121, 0.43712398, 0.06610783],
       [0.01160988, 0.91878587, 0.24575382, 0.2464967 ],
       [0.97115076, 0.42578571, 0.20855709, 0.97858441]])

Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [14]:
np.zeros([2,3,4],dtype = int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

# Array Operations

Given two 1-dimensional arrays, perform element-wise addition,
subtraction, multiplication, and division.

In [15]:

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# addition
addition = array1 + array2

# subtraction
subtraction = array1 - array2

# multiplication
multiplication = array1 * array2

# division
division = array1 / array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Calculate the mean, median, and standard deviation of a given 1-
dimensional array.

In [16]:
#mean
mean = np.mean(array1)

#median
median = np.median(array1)

#standard deviation
std_deviation = np.std(array1)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_deviation)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).

In [22]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array = array1.reshape(3, 4)

print("Reshaped Array:\n", reshaped_array)


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 3. Array Indexing and Slicing:

Extract the first row and last column of a 2-dimensional array.

In [25]:
array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
first_row = array[0, :]
last_column = array[:, -1]

print("First Row:", first_row)
print("Last Column:", last_column)


First Row: [1 2 3 4]
Last Column: [ 4  8 12]


Reverse the Order of Elements in a 1-Dimensional Array

In [23]:
array1d = np.array([1, 2, 3, 4, 5])


reversed_array = array1d[::-1]

reversed_array

array([5, 4, 3, 2, 1])

Select elements from a 2-dimensional array that satisfy a specific
condition (e.g., values greater than a certain threshold).

In [26]:
array[array>5]

array([ 6,  7,  8,  9, 10, 11, 12])

## 4. Array Broadcasting:

Add a scalar value to each element of a 2-dimensional array.

In [27]:
scalar = 5
added_array = array +scalar
added_array

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

Multiply a 1-Dimensional Array with a 2-Dimensional Array Using Broadcasting

In [28]:
array1d = np.array([1, 2, 3, 4])
array2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

result_array = array2d * array1d
result_array

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48]])

# 5. Linear Algebra:

Calculate the dot product of two 1-dimensional arrays.

In [29]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

dot_product = np.dot(array1, array2)
dot_product

32

Compute the Matrix Multiplication of Two 2-Dimensional Arrays

In [30]:
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])


matrix_product = np.matmul(matrix1, matrix2)

print("Matrix Product:\n", matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


Find the Inverse and Determinant of a Square Matrix

In [31]:
square_matrix = np.array([[1, 2],
                          [3, 4]])
determinant = np.linalg.det(square_matrix)
inverse_matrix = np.linalg.inv(square_matrix)

print("Determinant:", determinant)
print("Inverse Matrix:\n", inverse_matrix)

Determinant: -2.0000000000000004
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
